name: build

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    if: github.repository == 'rmyorston/busybox-w32' || github.repository == 'dscho/busybox-w32' || github.repository == 'berlin4apk/busybox-w32'
    runs-on: windows-2022
  defaults:
    run:
      shell: msys2 {0}
  strategy:
    matrix:
      include:
        - { sys: mingw64, env: x86_64 }
        - { sys: mingw32, env: i686 }
        - { sys: ucrt64,  env: ucrt-x86_64 }  # Experimental!
        - { sys: clang64, env: clang-x86_64 } # Experimental!
      steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        install: mingw-w64-${{matrix.env}}-openssl
 #   steps:
#  - uses: msys2/setup-msys2@v2
 #   with:
 #     update: false
 #     install: >-
 #       base-devel
  #      git
  #- run: git config --global core.autocrlf input
  #  shell: bash
    - uses: actions/checkout@v2
  #  - name: restrict PATH to msys64 (and Windows)
  #    shell: bash
 #     run: echo 'PATH=/c/msys64/usr/bin:/c/msys64/bin:/usr/bin/:/bin:/c/Windows/system32' >>$GITHUB_ENV
    - name: mingw64_defconfig
      #shell: /c/msys64/bin/bash
      run: |
        # We do not _actually_ cross-compile
        sed -i 's/^\(CONFIG_CROSS_COMPILER_PREFIX=\).*/\1""/' configs/mingw*

        make -j$(nproc) mingw64_defconfig
    - name: build busybox.exe
      shell: bash
      run: make -j$(nproc) busybox.exe
    - name: upload busybox artifact
      uses: actions/upload-artifact@v2
      with:
        name: busybox
        path: busybox.exe
